### ISSUE TITLE
Add image to the GUI

### ISSUE THREAD

**Issue by sethcenterbar** [michaelbrooks1234/TkinterAPOD_App#1]
It would be dope if this showed an image. 

https://www.c-sharpcorner.com/blogs/basics-for-displaying-image-in-tkinter-python

**Comment by RasPiPkr** [comment]
Hi @sethcenterbar,

I was looking through issues using tag tkinter to look for something to do and I come across this issue.

@michaelbrooks1234 am I ok to help out?

**Comment by michaelbrooks1234** [comment]
@RasPiPkr Of course, some help right now would be exactly what I need. I am having trouble getting image data from a url and putting it on a canvas/label. Some help would definitely be appreciated. Thanks.

**Comment by RasPiPkr** [comment]
![screenshot](https://user-images.githubusercontent.com/48888522/98845922-46426880-2446-11eb-9a16-0088ba356082.png)

If the picture sizes are different for each day you may have to resize the images in the code as I reduce the picture size to fit this picture.

**Comment by michaelbrooks1234** [comment]
I changed the code a little bit so that there is a slot for both the description and the image. It should work perfectly now. Thanks for the help!

**Comment by RasPiPkr** [comment]
Awesome, I’m glad I could help 👍

**Comment by RasPiPkr** [comment]
Just checked your change and this looks great having both onscreen. :thumbsup:
